/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGeneratorRouteImport } from './routes/_authenticated/generator'
import { Route as AuthenticatedGenerationRouteImport } from './routes/_authenticated/generation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivateRouteImport } from './routes/_authenticated/activate'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as ApiVideoStatusJobIdRouteImport } from './routes/api/video-status.$jobId'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as ApiPublicHooksVideoProgressRouteImport } from './routes/api/public/hooks/video-progress'
import { Route as ApiPublicHooksAutomationPlanRouteImport } from './routes/api/public/hooks/automation-plan'
import { Route as ApiPublicWebhooksPaymentsProviderRouteImport } from './routes/api/public/webhooks/payments.$provider'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeneratorRoute = AuthenticatedGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGenerationRoute = AuthenticatedGenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivateRoute = AuthenticatedActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiVideoStatusJobIdRoute = ApiVideoStatusJobIdRouteImport.update({
  id: '/api/video-status/$jobId',
  path: '/api/video-status/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksVideoProgressRoute =
  ApiPublicHooksVideoProgressRouteImport.update({
    id: '/api/public/hooks/video-progress',
    path: '/api/public/hooks/video-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationPlanRoute =
  ApiPublicHooksAutomationPlanRouteImport.update({
    id: '/api/public/hooks/automation-plan',
    path: '/api/public/hooks/automation-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaymentsProviderRoute =
  ApiPublicWebhooksPaymentsProviderRouteImport.update({
    id: '/api/public/webhooks/payments/$provider',
    path: '/api/public/webhooks/payments/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generation': typeof AuthenticatedGenerationRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/video-status/$jobId': typeof ApiVideoStatusJobIdRoute
  '/api/public/hooks/automation-plan': typeof ApiPublicHooksAutomationPlanRoute
  '/api/public/hooks/video-progress': typeof ApiPublicHooksVideoProgressRoute
  '/api/public/webhooks/payments/$provider': typeof ApiPublicWebhooksPaymentsProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generation': typeof AuthenticatedGenerationRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/video-status/$jobId': typeof ApiVideoStatusJobIdRoute
  '/api/public/hooks/automation-plan': typeof ApiPublicHooksAutomationPlanRoute
  '/api/public/hooks/video-progress': typeof ApiPublicHooksVideoProgressRoute
  '/api/public/webhooks/payments/$provider': typeof ApiPublicWebhooksPaymentsProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/activate': typeof AuthenticatedActivateRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generation': typeof AuthenticatedGenerationRoute
  '/_authenticated/generator': typeof AuthenticatedGeneratorRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/video-status/$jobId': typeof ApiVideoStatusJobIdRoute
  '/api/public/hooks/automation-plan': typeof ApiPublicHooksAutomationPlanRoute
  '/api/public/hooks/video-progress': typeof ApiPublicHooksVideoProgressRoute
  '/api/public/webhooks/payments/$provider': typeof ApiPublicWebhooksPaymentsProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accounts'
    | '/activate'
    | '/admin'
    | '/automation'
    | '/dashboard'
    | '/generation'
    | '/generator'
    | '/history'
    | '/integrations'
    | '/schedule'
    | '/api/generate-video'
    | '/settings/integrations'
    | '/api/video-status/$jobId'
    | '/api/public/hooks/automation-plan'
    | '/api/public/hooks/video-progress'
    | '/api/public/webhooks/payments/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accounts'
    | '/activate'
    | '/admin'
    | '/automation'
    | '/dashboard'
    | '/generation'
    | '/generator'
    | '/history'
    | '/integrations'
    | '/schedule'
    | '/api/generate-video'
    | '/settings/integrations'
    | '/api/video-status/$jobId'
    | '/api/public/hooks/automation-plan'
    | '/api/public/hooks/video-progress'
    | '/api/public/webhooks/payments/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/accounts'
    | '/_authenticated/activate'
    | '/_authenticated/admin'
    | '/_authenticated/automation'
    | '/_authenticated/dashboard'
    | '/_authenticated/generation'
    | '/_authenticated/generator'
    | '/_authenticated/history'
    | '/_authenticated/integrations'
    | '/_authenticated/schedule'
    | '/api/generate-video'
    | '/_authenticated/settings/integrations'
    | '/api/video-status/$jobId'
    | '/api/public/hooks/automation-plan'
    | '/api/public/hooks/video-progress'
    | '/api/public/webhooks/payments/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiVideoStatusJobIdRoute: typeof ApiVideoStatusJobIdRoute
  ApiPublicHooksAutomationPlanRoute: typeof ApiPublicHooksAutomationPlanRoute
  ApiPublicHooksVideoProgressRoute: typeof ApiPublicHooksVideoProgressRoute
  ApiPublicWebhooksPaymentsProviderRoute: typeof ApiPublicWebhooksPaymentsProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generator': {
      id: '/_authenticated/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AuthenticatedGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generation': {
      id: '/_authenticated/generation'
      path: '/generation'
      fullPath: '/generation'
      preLoaderRoute: typeof AuthenticatedGenerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activate': {
      id: '/_authenticated/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthenticatedActivateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/video-status/$jobId': {
      id: '/api/video-status/$jobId'
      path: '/api/video-status/$jobId'
      fullPath: '/api/video-status/$jobId'
      preLoaderRoute: typeof ApiVideoStatusJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/video-progress': {
      id: '/api/public/hooks/video-progress'
      path: '/api/public/hooks/video-progress'
      fullPath: '/api/public/hooks/video-progress'
      preLoaderRoute: typeof ApiPublicHooksVideoProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-plan': {
      id: '/api/public/hooks/automation-plan'
      path: '/api/public/hooks/automation-plan'
      fullPath: '/api/public/hooks/automation-plan'
      preLoaderRoute: typeof ApiPublicHooksAutomationPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/payments/$provider': {
      id: '/api/public/webhooks/payments/$provider'
      path: '/api/public/webhooks/payments/$provider'
      fullPath: '/api/public/webhooks/payments/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksPaymentsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedActivateRoute: typeof AuthenticatedActivateRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerationRoute: typeof AuthenticatedGenerationRoute
  AuthenticatedGeneratorRoute: typeof AuthenticatedGeneratorRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedActivateRoute: AuthenticatedActivateRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerationRoute: AuthenticatedGenerationRoute,
  AuthenticatedGeneratorRoute: AuthenticatedGeneratorRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiVideoStatusJobIdRoute: ApiVideoStatusJobIdRoute,
  ApiPublicHooksAutomationPlanRoute: ApiPublicHooksAutomationPlanRoute,
  ApiPublicHooksVideoProgressRoute: ApiPublicHooksVideoProgressRoute,
  ApiPublicWebhooksPaymentsProviderRoute:
    ApiPublicWebhooksPaymentsProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
